name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Install VSCE
        run: npm install -g vsce

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Tag Version
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Package Extension
        run: vsce package

      - name: Publish Extension
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
  notify:
    name: Discord Notification
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          description: |
            Build #${{ github.run_number }}
            ```Ducke Theme: ${{ needs.deploy.outputs.version }}```
